#!/bin/bash
#PBS -N run_mcmc
#PBS -q default
#PBS -l nodes=3:ppn=12,walltime=100:00:00
#PBS -V
##PBS -m bae -M slan@caltech.edu
#PBS -o ./${MCMC}_${ALG}_${SEED}.o$PBS_JOBID
#PBS -e ./${MCMC}_${ALG}_${SEED}.e$PBS_JOBID

# load FEniCS environment
# source ${HOME}/FEniCS-1.6.0/fenics_1.6.0.sh

# go to working directory
cd ~/FIS-MCMC/code/RANS/RANS_bip

# run python script
./rans_mcmc.sh ${MCMC} ${ALG} ${SEED} ${NCORE}